version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: my_ecommerce
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: