import { Metadata } from "next";
import React from "react";

type Props = {
  children: React.ReactNode;
};
export const metadata: Metadata = {
  title: "SignUp | Ecommerce",
  description: "Generated by create next app",
};
export default function SignUpLayout({ children }: Props) {
  return <main>{children}</main>;
}
